apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: frugalia-mcp
  namespace: kagent
  labels:
    kagent.dev/discovery: disabled
spec:
  transportType: stdio
  deployment:
    image: us-central1-docker.pkg.dev/level-elevator-474703-b3/mcp/frugalia-mcp:b0.0.8
    cmd: "python"
    args:
    - "src/main.py"
    port: 3000
    env:
      PROMETHEUS_URL: "http://prometheus-kube-prometheus-prometheus.monitoring:9090"
