apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: agw-mcp-servers
  namespace: kagent
spec:
  description: "Agentgateway as MCP gateway for MCP servers"
  protocol: STREAMABLE_HTTP
  sseReadTimeout: 5m0s
  terminateOnClose: true
  timeout: 30s
  url: http://mcp-gateway.kagent.svc.cluster.local:3000
